name: Team awesome's approval workflowved
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    name: Label when approved
    
    steps:
      - uses: action/label-when-approved-action@master
      - name: automate approval
        env:
          APPROVALS: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: Approved
